name: Forecast
on:
  push:
    branches: main
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:
jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch weather
        run: bash ./wttr.sh

      - name: Send email
        uses: dawidd6/action-send-mail@v2.4.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          subject: Today Forecast
          body: file://weather.html
          from: Ronnie
          to: ronniesong0809@gmail.com
          content_type: text/html
