name: Forecast
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch weather
        run: bash ./wttr.sh
